spring:
  application:
    name: order-client
  datasource:
    username: root
    password: hibernate
    url: jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9090
