package com.mangmangbang.pojo;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.username
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.face_image
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    private String faceImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.face_image_big
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    private String faceImageBig;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.nickname
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.qrcode
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    private String qrcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.cid
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    private String cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.username
     *
     * @return the value of users.username
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.username
     *
     * @param username the value for users.username
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.face_image
     *
     * @return the value of users.face_image
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    public String getFaceImage() {
        return faceImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.face_image
     *
     * @param faceImage the value for users.face_image
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    public void setFaceImage(String faceImage) {
        this.faceImage = faceImage == null ? null : faceImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.face_image_big
     *
     * @return the value of users.face_image_big
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    public String getFaceImageBig() {
        return faceImageBig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.face_image_big
     *
     * @param faceImageBig the value for users.face_image_big
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    public void setFaceImageBig(String faceImageBig) {
        this.faceImageBig = faceImageBig == null ? null : faceImageBig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.nickname
     *
     * @return the value of users.nickname
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.nickname
     *
     * @param nickname the value for users.nickname
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.qrcode
     *
     * @return the value of users.qrcode
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    public String getQrcode() {
        return qrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.qrcode
     *
     * @param qrcode the value for users.qrcode
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    public void setQrcode(String qrcode) {
        this.qrcode = qrcode == null ? null : qrcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.cid
     *
     * @return the value of users.cid
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.cid
     *
     * @param cid the value for users.cid
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", faceImage=").append(faceImage);
        sb.append(", faceImageBig=").append(faceImageBig);
        sb.append(", nickname=").append(nickname);
        sb.append(", qrcode=").append(qrcode);
        sb.append(", cid=").append(cid);
        sb.append("]");
        return sb.toString();
    }
}