package com.mangmangbang.dao;

import com.mangmangbang.pojo.ChatMessage;
import com.mangmangbang.pojo.ChatMessageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ChatMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    long countByExample(ChatMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    int deleteByExample(ChatMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    int insert(ChatMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    int insertSelective(ChatMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    List<ChatMessage> selectByExample(ChatMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    ChatMessage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") ChatMessage record, @Param("example") ChatMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    int updateByExample(@Param("record") ChatMessage record, @Param("example") ChatMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    int updateByPrimaryKeySelective(ChatMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    int updateByPrimaryKey(ChatMessage record);
}