package com.mangmangbang.dao;

import com.mangmangbang.pojo.MyFriends;
import com.mangmangbang.pojo.MyFriendsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MyFriendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    long countByExample(MyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    int deleteByExample(MyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    int insert(MyFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    int insertSelective(MyFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    List<MyFriends> selectByExample(MyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    MyFriends selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") MyFriends record, @Param("example") MyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    int updateByExample(@Param("record") MyFriends record, @Param("example") MyFriendsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    int updateByPrimaryKeySelective(MyFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friends
     *
     * @mbg.generated Fri Oct 11 15:10:17 CST 2019
     */
    int updateByPrimaryKey(MyFriends record);
}